### ISSUE TITLE
Bundle up an inputs.conf

### ISSUE THREAD

**Issue by santacruzpl-lit** [LukeMurphey/splunk-network-tools#2]
Just an idea,
Include a few default stanza for scheduling tests.

[script://./bin/speedtest.py]
interval = 1800
sourcetype = speedtest
source = speedtest
index = main
disabled = true

**Comment by LukeMurphey** [comment]
I added a new input type that allows you to schedule Internet connection speed-tests in version 1.0. See https://splunkbase.splunk.com/app/3491/ to download it.

To use it, just make a new input in Splunk; look for the type of input titled "Internet Connection Speedtest".
